# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20151107_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
